#!/bin/bash

################ LINUX script ################
#SSM_NAME='ssm_coordinator'
#process=`grep libssm.so /proc/*/maps | cut -d / -f 3 | uniq`

#全てのプロセスにSIGINTを送る
#for i in ${process}
#do
#	name=`cat "/proc/$i/cmdline" | tr '\0' ' ' | cut -d ' '  -f1`
#	if [ ${name} = ${SSM_NAME} ]; then
#		continue;
#	fi
#	echo $i  $name
#	kill -s SIGINT $i
#	sleep 0.01
#done

# last shutdown ssm_coordinator
#sleep 1
#killall -s SIGINT ${SSM_NAME} #<--for Linux?
#kill -SIGINT `grep libssm.so /proc/*/maps | cut -d / -f 3 | uniq`



################# OSX script #################

# define variable
SSM_NAME='ssm_coordinator'
COORDINATOR_PID=`pgrep ${SSM_NAME}`
PID=`ps | awk 'NR>1' | awk '{print $1}'`

# sending all process to signal "SIGINT"
# excluding coordinator
echo "kill ssm process..."
for i in ${PID}
do
	if [ $i != ${COORDINATOR_PID} ]; then
		vmmap $i | grep libssm
		if [ $? -eq 0 ]; then
			kill -SIGINT $i 
		fi
	fi
done

# shutdown ssm_coordinator
echo "kill ssm_coordinator..."
sleep 0.5
killall -SIGINT ${SSM_NAME} > /dev/null 2>&1

# last shutdown all process
echo "kill all ssm process again..."
for i in ${PID}
do
	vmmap $i | grep libssm
	if [ $? -eq 0 ]; then
		kill -SIGINT $i 
	fi
done
